# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutubeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/YouTube'
  pod 'SDWebImage'
  pod 'youtube-ios-player-helper'

  # Pods for YoutubeApp

  target 'YoutubeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YoutubeAppUITests' do
    # Pods for testing
  end

end
